name: flight_booking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^10.1.0
  flutter_spinkit: ^5.1.0
  email_validator: ^2.1.16
  flutter_pw_validator: ^1.4.2
  http: ^0.13.4
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  firebase_storage: ^10.3.4
  circular_bottom_navigation: ^2.1.0
  flutter_advanced_drawer: ^1.3.2
  flutter_slidable: ^2.0.0
  awesome_notifications: ^0.6.21
  geolocator: ^9.0.0
  location: ^4.4.0
  permission_handler: ^10.0.0
  marker_icon: ^0.7.1
  google_maps_flutter: ^2.1.10
  intl: ^0.17.0
  share: ^2.0.4
  flutter_rating_bar: ^4.0.1
  flutter_email_sender: ^5.1.0
  file_picker: ^5.0.1
  mailer: ^5.2.0
  hyperpay: ^1.0.0-dev.2
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - Images/SplashScreen/
    - Images/ForgetPasswordScreen/
    - Images/ChangeMyPasswordScreen/
    - Images/UserInformationScreen/
    - Images/OTPScreen/
    - Images/HomeScreen/
    - Images/SettingsScreen/
    - Images/PrivacyPolicyScreen/
    - Images/TermsConditionsScreen/
    - Images/PaymentScreen/
    - Images/FlightsDetailsScreen/
    - Images/FavouritesScreen/
    - Images/ContactUsScreen/
    - Images/RateAppScreen/
    - .env

